experiment_name: ???

defaults:
  - model: dregncf
  - dataset: gowalla

log:
  silent: False
  file_path: runs/log/
  code_path: runs/code_backup/
  model_path: runs/model_backup/
  level: INFO

environment:
  device: 'cuda:0'
  num_workers: 16

evaluation:
  topK: [5, 10, 20, 50]
